---
- include: packages.yml
- include: assets.yml

- service: name=mysqld state=restarted enabled=yes

- service: name=php-fpm state=restarted enabled=yes

- service: name=httpd state=restarted enabled=yes
